### PR TITLE
Reactive Summit 2016

### PR DESCRIPTION
**Pull request by manuzhang**
[call for proposals](https://www.reactivesummit.org/call-for-proposals)

### CODE REVIEW

**Comment by kkasravi** [comment]
@manuzhang we should only merge if the paper is accepted correct?

**Comment by manuzhang** [comment]
@kkasravi yes, maybe after the conference. Then we update this PR with slides and other information.

**Comment by kkasravi** [comment]
talks submitted on akka-streams and gearpump.

**Comment by kkasravi** [comment]
+1

**Pull request merged**
