### PR TITLE
Strata + Hadoop World,  Singapore, 2016

### PR DESCRIPTION
**Pull request by manuzhang**
[call for proposals](http://conferences.oreilly.com/strata/hadoop-big-data-sg/public/cfp/475?imm_mid=0e37bf&cmp=em-data-confpro-na-stsg16_em1_cfp) closes 11:59pm 06/21/2016 SGT.

### CODE REVIEW

**Comment by manuzhang** [comment]
this is due next week.

**Comment by kkasravi** [comment]
I'll submit a paper late this week or earlier next week.

**Comment by manuzhang** [comment]
Sean gave a general introduction to Gearpump last year so we'd better have some novelty. We get plenty of time.

**Comment by manuzhang** [comment]
rejected 😞

**Pull request closed without merging**
